/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Objects;
import javax.swing.JPanel;

/**
 *
 * @author carlo
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        panelContenedor.setLayout(new CardLayout());
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        botonInicio = new javax.swing.JButton();
        botonPacientes = new javax.swing.JButton();
        botonCitas = new javax.swing.JButton();
        botonConfiguracion = new javax.swing.JButton();
        botonExpediente = new javax.swing.JButton();
        botonFacturas = new javax.swing.JButton();
        botonInventario = new javax.swing.JButton();
        botonMedicamentos = new javax.swing.JButton();
        botonMedicos = new javax.swing.JButton();
        botonNotificaciones = new javax.swing.JButton();
        botonPagos = new javax.swing.JButton();
        botonRecetas = new javax.swing.JButton();
        botonTratamientos = new javax.swing.JButton();
        botonUsuarios = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estar Bien");
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(1250, 800));

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonInicio.setBackground(new java.awt.Color(255, 255, 255));
        botonInicio.setText("Inicio");
        botonInicio.setBorderPainted(false);
        botonInicio.setContentAreaFilled(false);
        botonInicio.setFocusPainted(false);
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });

        botonPacientes.setBackground(new java.awt.Color(255, 255, 255));
        botonPacientes.setText("Pacientes");
        botonPacientes.setBorderPainted(false);
        botonPacientes.setContentAreaFilled(false);
        botonPacientes.setFocusPainted(false);
        botonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPacientesActionPerformed(evt);
            }
        });

        botonCitas.setBackground(new java.awt.Color(255, 255, 255));
        botonCitas.setText("Citas");
        botonCitas.setBorderPainted(false);
        botonCitas.setContentAreaFilled(false);
        botonCitas.setFocusPainted(false);
        botonCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCitasActionPerformed(evt);
            }
        });

        botonConfiguracion.setText("Configuración");
        botonConfiguracion.setBorderPainted(false);
        botonConfiguracion.setContentAreaFilled(false);
        botonConfiguracion.setFocusPainted(false);
        botonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfiguracionActionPerformed(evt);
            }
        });

        botonExpediente.setText("Expediente");
        botonExpediente.setBorderPainted(false);
        botonExpediente.setContentAreaFilled(false);
        botonExpediente.setFocusPainted(false);
        botonExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExpedienteActionPerformed(evt);
            }
        });

        botonFacturas.setText("Facturas");
        botonFacturas.setBorderPainted(false);
        botonFacturas.setContentAreaFilled(false);
        botonFacturas.setFocusPainted(false);
        botonFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacturasActionPerformed(evt);
            }
        });

        botonInventario.setText("Inventario");
        botonInventario.setBorderPainted(false);
        botonInventario.setContentAreaFilled(false);
        botonInventario.setFocusPainted(false);
        botonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioActionPerformed(evt);
            }
        });

        botonMedicamentos.setText("Medicamentos");
        botonMedicamentos.setBorderPainted(false);
        botonMedicamentos.setContentAreaFilled(false);
        botonMedicamentos.setFocusPainted(false);
        botonMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMedicamentosActionPerformed(evt);
            }
        });

        botonMedicos.setText("Medicos");
        botonMedicos.setBorderPainted(false);
        botonMedicos.setContentAreaFilled(false);
        botonMedicos.setFocusPainted(false);
        botonMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMedicosActionPerformed(evt);
            }
        });

        botonNotificaciones.setText("Notificaciones");
        botonNotificaciones.setBorderPainted(false);
        botonNotificaciones.setContentAreaFilled(false);
        botonNotificaciones.setFocusPainted(false);
        botonNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNotificacionesActionPerformed(evt);
            }
        });

        botonPagos.setText("Pagos");
        botonPagos.setBorderPainted(false);
        botonPagos.setContentAreaFilled(false);
        botonPagos.setFocusPainted(false);
        botonPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagosActionPerformed(evt);
            }
        });

        botonRecetas.setText("Recetas");
        botonRecetas.setBorderPainted(false);
        botonRecetas.setContentAreaFilled(false);
        botonRecetas.setFocusPainted(false);
        botonRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecetasActionPerformed(evt);
            }
        });

        botonTratamientos.setText("Tratamientos");
        botonTratamientos.setBorderPainted(false);
        botonTratamientos.setContentAreaFilled(false);
        botonTratamientos.setFocusPainted(false);
        botonTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTratamientosActionPerformed(evt);
            }
        });

        botonUsuarios.setText("Usuarios");
        botonUsuarios.setBorderPainted(false);
        botonUsuarios.setContentAreaFilled(false);
        botonUsuarios.setFocusPainted(false);
        botonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonPacientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonConfiguracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonExpediente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonFacturas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMedicamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMedicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNotificaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRecetas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonTratamientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonUsuarios)
                .addContainerGap(907, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInicio)
                    .addComponent(botonPacientes)
                    .addComponent(botonCitas)
                    .addComponent(botonConfiguracion)
                    .addComponent(botonExpediente)
                    .addComponent(botonFacturas)
                    .addComponent(botonInventario)
                    .addComponent(botonMedicamentos)
                    .addComponent(botonMedicos)
                    .addComponent(botonNotificaciones)
                    .addComponent(botonPagos)
                    .addComponent(botonRecetas)
                    .addComponent(botonTratamientos)
                    .addComponent(botonUsuarios))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, java.awt.BorderLayout.NORTH);

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2184, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        getContentPane().add(panelContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        mostrarPanel("Inicio", new PanelInicio());
    }//GEN-LAST:event_botonInicioActionPerformed

    private void botonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPacientesActionPerformed
        mostrarPanel("Pacientes", new PanelPacientes());
    }//GEN-LAST:event_botonPacientesActionPerformed

    private void botonCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCitasActionPerformed
        mostrarPanel("Citas", new PanelCitas());
    }//GEN-LAST:event_botonCitasActionPerformed

    private void botonExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExpedienteActionPerformed
        mostrarPanel("Expediente", new PanelExpedientes());
    }//GEN-LAST:event_botonExpedienteActionPerformed

    private void botonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfiguracionActionPerformed
        mostrarPanel("Configuracion", new PanelConfiguracion());
    }//GEN-LAST:event_botonConfiguracionActionPerformed

    private void botonFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacturasActionPerformed
        mostrarPanel("Facturas", new PanelFacturas());
    }//GEN-LAST:event_botonFacturasActionPerformed

    private void botonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioActionPerformed
        mostrarPanel("Inventario", new PanelInventario());
    }//GEN-LAST:event_botonInventarioActionPerformed

    private void botonMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMedicamentosActionPerformed
        mostrarPanel("Medicamentos", new PanelMedicamentos());
    }//GEN-LAST:event_botonMedicamentosActionPerformed

    private void botonMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMedicosActionPerformed
        mostrarPanel("Medicos", new PanelMedicos());
    }//GEN-LAST:event_botonMedicosActionPerformed

    private void botonNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNotificacionesActionPerformed
        mostrarPanel("Notificaciones", new PanelNotificaciones());
    }//GEN-LAST:event_botonNotificacionesActionPerformed

    private void botonPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagosActionPerformed
        mostrarPanel("Pagos", new PanelPagos());
    }//GEN-LAST:event_botonPagosActionPerformed

    private void botonRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecetasActionPerformed
        mostrarPanel("Recetas", new PanelReceta());
    }//GEN-LAST:event_botonRecetasActionPerformed

    private void botonTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTratamientosActionPerformed
        mostrarPanel("Tratamientos", new PanelTratamientos());
    }//GEN-LAST:event_botonTratamientosActionPerformed

    private void botonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuariosActionPerformed
        mostrarPanel("Usuarios", new PanelUsuarios());
    }//GEN-LAST:event_botonUsuariosActionPerformed

    /**
     * Muestra un panel específico en el contenedor utilizando CardLayout. Si el panel ya existe, simplemente lo muestra. Si no existe, lo añade al contenedor antes de mostrarlo.
     *
     * @param nombrePanel Identificador único del panel
     * @param panel Panel a mostrar
     */
    public void mostrarPanel(String nombrePanel, JPanel panel) {
        CardLayout layout = (CardLayout) panelContenedor.getLayout();

        // Verifica si el panel ya existe en el contenedor
        boolean panelExiste = false;
        for (Component comp : panelContenedor.getComponents()) {
            if (nombrePanel.equals(comp.getName())) {
                panelExiste = true;
                break;
            }
        }

        // Si el panel no existe, lo añade al contenedor
        if (!panelExiste) {
            panel.setName(nombrePanel);
            panelContenedor.add(panel, nombrePanel);
        }

        // Muestra el panel y actualiza la interfaz
        layout.show(panelContenedor, nombrePanel);
        panelContenedor.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCitas;
    private javax.swing.JButton botonConfiguracion;
    private javax.swing.JButton botonExpediente;
    private javax.swing.JButton botonFacturas;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonInventario;
    private javax.swing.JButton botonMedicamentos;
    private javax.swing.JButton botonMedicos;
    private javax.swing.JButton botonNotificaciones;
    private javax.swing.JButton botonPacientes;
    private javax.swing.JButton botonPagos;
    private javax.swing.JButton botonRecetas;
    private javax.swing.JButton botonTratamientos;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
