/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import control.UsuarioJpaController;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;

/**
 *
 * @author carlo
 */
public class PanelUsuarios extends javax.swing.JPanel {
    private UsuarioJpaController cUsuario;
    private EntityManagerFactory emf;
    private List<Usuario> usuarios;
    private DefaultListModel<Usuario> model;
    /**
     * Creates new form PanelUsuarios
     */
    public PanelUsuarios() {
        initComponents();
        emf = Persistence.createEntityManagerFactory("EstarBienPU");
        cUsuario = new UsuarioJpaController(emf);
        usuarios = cUsuario.findUsuarioEntities();
        model = new DefaultListModel<Usuario>();
        listaUsuarios.setModel(model);
        llenarDatos();
    }
    public void llenarDatos() {
        model.clear(); // Limpiar lista antes de llenarla
        for (Usuario u : usuarios) {
            model.addElement(u); // Mostrar nombre del usuario
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosUsuario = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        editarUsuario = new javax.swing.JButton();
        agregarUusario = new javax.swing.JButton();
        eliminarUsuario = new javax.swing.JButton();
        cargarUsuarioB = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        listaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaUsuarios);

        add(jScrollPane2, java.awt.BorderLayout.LINE_START);

        datosUsuario.setColumns(20);
        datosUsuario.setRows(5);
        jScrollPane1.setViewportView(datosUsuario);

        add(jScrollPane1, java.awt.BorderLayout.LINE_END);

        jLabel1.setText("Usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);

        editarUsuario.setText("Editar Usuario");
        editarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioActionPerformed(evt);
            }
        });

        agregarUusario.setText("Agregar Usuario");
        agregarUusario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarUusarioActionPerformed(evt);
            }
        });

        eliminarUsuario.setText("Eliminar Usuario");
        eliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarUsuarioActionPerformed(evt);
            }
        });

        cargarUsuarioB.setText("Cargar Usuario");
        cargarUsuarioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarUsuarioBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(editarUsuario)
                .addGap(18, 18, 18)
                .addComponent(agregarUusario)
                .addGap(18, 18, 18)
                .addComponent(eliminarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cargarUsuarioB)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarUsuario)
                    .addComponent(agregarUusario)
                    .addComponent(eliminarUsuario)
                    .addComponent(cargarUsuarioB))
                .addGap(32, 32, 32))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void editarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsuarioActionPerformed
        
    }//GEN-LAST:event_editarUsuarioActionPerformed

    private void listaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaUsuariosMouseClicked
       Usuario usuarioSeleccionado = (Usuario) listaUsuarios.getSelectedValue();
    if (usuarioSeleccionado != null) {
        String datos = "Nombre de Usuario: " + usuarioSeleccionado.getNombreUsuario() + "\n"
                     + "Rol: " + usuarioSeleccionado.getRol()+ "\n"
                     + "IdUsuario: " + usuarioSeleccionado.getIdUsuario()+ "\n";
        datosUsuario.setText(datos);
    }
    }//GEN-LAST:event_listaUsuariosMouseClicked

    private void eliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarUsuarioActionPerformed

    private void agregarUusarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarUusarioActionPerformed
        Usuario usuarioSeleccionado = (Usuario) listaUsuarios.getSelectedValue();
        
    }//GEN-LAST:event_agregarUusarioActionPerformed

    private void cargarUsuarioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarUsuarioBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarUsuarioBActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarUusario;
    private javax.swing.JButton cargarUsuarioB;
    private javax.swing.JTextArea datosUsuario;
    private javax.swing.JButton editarUsuario;
    private javax.swing.JButton eliminarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Usuario> listaUsuarios;
    // End of variables declaration//GEN-END:variables
}
