/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import control.Sesion;
import java.util.Date;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import modelo.Usuario;

/**
 *
 * @author carlo
 */
public class PanelConfiguracion extends javax.swing.JPanel {
    boolean modoOscuro = true;
    /**
     * Creates new form PanelConfiguracion
     */
    public PanelConfiguracion() {
        initComponents();
    }
    public void mostrarBienvenida(Usuario usuario) {
        String nombreCompleto = "";
        String rol = usuario.getRol();
        
        // Determinar el nombre según el rol
        switch(rol.toLowerCase()) {
            case "administrador":
                if(usuario.getAdministrador() != null) {
                    nombreCompleto = usuario.getAdministrador().getNombre() +
                            "\n --> Iniciaste Sesion: " + (new Date());
                }
                break;
            case "medico":
                if(usuario.getMedico() != null) {
                    nombreCompleto = usuario.getMedico().getNombre() +
                            "\n --> Iniciaste Sesion: " + (new Date());
                }
                break;
            case "paciente":
                if(usuario.getPaciente() != null) {
                    nombreCompleto = usuario.getPaciente().getNombre() +
                            "\n --> Iniciaste Sesion: " + (new Date());
                }
                break;
        }
        
        usuarioTexto.setText("Bienvenido: " + nombreCompleto);
        rolTexto.setText("Rol: " + rol.substring(0, 1).toUpperCase() + rol.substring(1));
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioTexto = new javax.swing.JLabel();
        temaBoton = new javax.swing.JButton();
        rolTexto = new javax.swing.JLabel();
        cerrarSesionBot = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1397, 882));
        setMinimumSize(new java.awt.Dimension(1397, 882));

        usuarioTexto.setBackground(new java.awt.Color(255, 255, 255));
        usuarioTexto.setText("Panel Configuracion");

        temaBoton.setText("Oscuro");
        temaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaBotonActionPerformed(evt);
            }
        });

        rolTexto.setText("hola");

        cerrarSesionBot.setText("Cerrar Sesion");
        cerrarSesionBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(temaBoton)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(rolTexto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(usuarioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(cerrarSesionBot)))
                .addContainerGap(469, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(temaBoton)
                .addGap(124, 124, 124)
                .addComponent(usuarioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rolTexto)
                .addGap(49, 49, 49)
                .addComponent(cerrarSesionBot)
                .addContainerGap(560, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void temaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaBotonActionPerformed
        try {
            
        if (!modoOscuro) {
            FlatMacLightLaf.setup();
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            temaBoton.setText("Oscuro");
        } else {
            FlatDarculaLaf.setup();
            UIManager.setLookAndFeel(new FlatDarculaLaf());
            temaBoton.setText("Claro");
        }

        modoOscuro = !modoOscuro;

        // Aplica el nuevo LookAndFeel a toda la ventana principal
        SwingUtilities.updateComponentTreeUI(SwingUtilities.getWindowAncestor(this));

    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_temaBotonActionPerformed

    private void cerrarSesionBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBotActionPerformed
        Sesion.cerrarSesion();
        MainView mainView = (MainView) SwingUtilities.getWindowAncestor(this);
        mainView.ocultarTodosLosMenus();
        mainView.mostrarPanel("IniciarSesion", mainView.panelIniSes);
    }//GEN-LAST:event_cerrarSesionBotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesionBot;
    private javax.swing.JLabel rolTexto;
    private javax.swing.JButton temaBoton;
    private javax.swing.JLabel usuarioTexto;
    // End of variables declaration//GEN-END:variables
}
