/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Pagos;

import control.PagoJpaController;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author carlo
 */
public class PanelPagos extends javax.swing.JPanel {

    /**
     * 
     */
    
    
    public PanelPagos() {
        initComponents();
        panelFormularioDeslizante.setPreferredSize(new Dimension(0, panelFormularioDeslizante.getHeight()));
        panelFormularioDeslizante.setMinimumSize(new Dimension(0, panelFormularioDeslizante.getHeight()));
        panelFormularioDeslizante.setMaximumSize(new Dimension(0, panelFormularioDeslizante.getHeight()));
        panelFormularioDeslizante.revalidate();
        panelFormularioDeslizante.repaint();
        configurarListeners();
        pagoController = new PagoJpaController();
        modeloTablaHistorial = (DefaultTableModel) tablaHistorial.getModel();
        cargarTablaHistorial();
        // Configura el buscador
        buscador.setJTable(tablaHistorial);
    }

    
    //INICIO DE MÉTODOS PARA EL PANEL DESLIZANTE
    private void configurarListeners() {
        botonAgregar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                desplegarFormulario();
            }
        });

        botonActualizar.addActionListener(new ActionListener() { // Actualizar
            @Override
            public void actionPerformed(ActionEvent e) {
                desplegarFormulario(); // Misma lógica para modificar por ahora
                tituloPanelDeslizanteLabel.setText("Actualizar Pago");
            }
        });

        timerDeslizamiento = new Timer(15, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                animarDeslizamiento();
            }
        });

        botonCancelar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                retraerFormulario();
            }
        });
        
        // También añadir funcionalidad al botón guardar
        botonGuardar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Aquí iría la lógica para guardar el medicamento
                // Por ahora, solo cerramos el formulario
                retraerFormulario();
            }
        });
    }

    private void desplegarFormulario() {
        desplegado = true;
        timerDeslizamiento.start();
    }

    private void retraerFormulario() {
        desplegado = false;
        timerDeslizamiento.start();
    }


    private void animarDeslizamiento() {
        int anchoActual = panelFormularioDeslizante.getPreferredSize().width;
        int nuevoAncho;
        
        if (desplegado) {
            nuevoAncho = Math.min(anchoActual + velocidadDeslizamiento, anchoObjetivo);
        } else {
            nuevoAncho = Math.max(anchoActual - velocidadDeslizamiento, 0);
        }
        
        // Actualizar el tamaño del panel
        panelFormularioDeslizante.setPreferredSize(new Dimension(nuevoAncho, panelFormularioDeslizante.getHeight()));
        panelFormularioDeslizante.setMinimumSize(new Dimension(nuevoAncho, panelFormularioDeslizante.getHeight()));
        panelFormularioDeslizante.setMaximumSize(new Dimension(nuevoAncho, panelFormularioDeslizante.getHeight()));
        
        // Refrescar la visualización
        panelFormularioDeslizante.revalidate();
        panelFormularioDeslizante.repaint();
        revalidate();
        repaint();
        
        // Detener el timer cuando se alcanza el objetivo
        if ((desplegado && nuevoAncho == anchoObjetivo) || (!desplegado && nuevoAncho == 0)) {
            timerDeslizamiento.stop();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormularioDeslizante = new javax.swing.JPanel();
        tituloPanelDeslizanteLabel = new javax.swing.JLabel();
        nombrePacienteLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buscadorListaPacientes = new miscomponentes.JBuscadorLista();
        buscadorListaCita = new miscomponentes.JBuscadorLista();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        pacienteSeleccionadoLabel = new javax.swing.JLabel();
        citaSeleccionadaLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        estadoPagoComboBox = new javax.swing.JComboBox<>();
        panelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        buscador = new miscomponentes.JBuscador();
        botonAgregar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1397, 882));

        panelFormularioDeslizante.setBackground(new java.awt.Color(249, 249, 249));

        tituloPanelDeslizanteLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloPanelDeslizanteLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloPanelDeslizanteLabel.setText("Agregar Pago");

        nombrePacienteLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombrePacienteLabel.setForeground(new java.awt.Color(0, 0, 0));
        nombrePacienteLabel.setText("Nombre del paciente");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Número de Cita");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Folio de pago");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Estado del pago");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Monto Total:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha y hora de registro: ....");

        jScrollPane2.setViewportView(jList1);

        jList2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jScrollPane3.setViewportView(jList2);

        jLabel6.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Si no encuentra al paciente, posiblemente no esté registrado");

        pacienteSeleccionadoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pacienteSeleccionadoLabel.setForeground(new java.awt.Color(0, 0, 0));
        pacienteSeleccionadoLabel.setText("Paciente Seleccionado: ....");

        citaSeleccionadaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        citaSeleccionadaLabel.setForeground(new java.awt.Color(0, 0, 0));
        citaSeleccionadaLabel.setText("Cita Seleccionada: ....");

        jLabel7.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Si no encuentra la cita, posiblemente no esté registrada");

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormularioDeslizanteLayout = new javax.swing.GroupLayout(panelFormularioDeslizante);
        panelFormularioDeslizante.setLayout(panelFormularioDeslizanteLayout);
        panelFormularioDeslizanteLayout.setHorizontalGroup(
            panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioDeslizanteLayout.createSequentialGroup()
                                .addComponent(tituloPanelDeslizanteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioDeslizanteLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addContainerGap())))
                    .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                        .addGroup(panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                                .addComponent(nombrePacienteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7)
                                        .addGap(0, 52, Short.MAX_VALUE))
                                    .addComponent(buscadorListaPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormularioDeslizanteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                                .addGroup(panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFormularioDeslizanteLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(citaSeleccionadaLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFormularioDeslizanteLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(estadoPagoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pacienteSeleccionadoLabel)
                            .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscadorListaCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelFormularioDeslizanteLayout.setVerticalGroup(
            panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                        .addComponent(tituloPanelDeslizanteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(nombrePacienteLabel)
                        .addGap(10, 10, 10))
                    .addComponent(buscadorListaPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pacienteSeleccionadoLabel)
                .addGroup(panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscadorListaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormularioDeslizanteLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(citaSeleccionadaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estadoPagoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(panelFormularioDeslizanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        tablaHistorial.setBackground(new java.awt.Color(255, 255, 255));
        tablaHistorial.setForeground(new java.awt.Color(153, 153, 153));
        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Folio", "Paciente", "Estado", "Fecha y hora", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHistorial.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tablaHistorial);

        buscador.setBackground(new java.awt.Color(204, 204, 204));
        buscador.setForeground(new java.awt.Color(255, 255, 255));
        buscador.setJTable(tablaHistorial);
        buscador.setPlaceholder("Buscar pago...");

        botonAgregar.setText("Agregar Pago");

        botonActualizar.setText("Actualizar Pago");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                        .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFormularioDeslizante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFormularioDeslizante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void cargarTablaHistorial() {
        try {
            // Limpiar la tabla
            modeloTablaHistorial.setRowCount(0);

            // Obtener datos usando la instancia existente del controlador
            List<Object[]> datos = pagoController.obtenerDatosTabla();

            // Agregar datos
            for (Object[] fila : datos) {
                modeloTablaHistorial.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al cargar datos: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Para depuración
        }
    }
    
    public void actualizarTabla() {
        cargarTablaHistorial();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private miscomponentes.JBuscador buscador;
    private miscomponentes.JBuscadorLista buscadorListaCita;
    private miscomponentes.JBuscadorLista buscadorListaPacientes;
    private javax.swing.JLabel citaSeleccionadaLabel;
    private javax.swing.JComboBox<String> estadoPagoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nombrePacienteLabel;
    private javax.swing.JLabel pacienteSeleccionadoLabel;
    private javax.swing.JPanel panelFormularioDeslizante;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JLabel tituloPanelDeslizanteLabel;
    // End of variables declaration//GEN-END:variables
    //Declaración de variables modificables
    //Variables para cargar Tabla
    private DefaultTableModel modeloTablaHistorial;
    private PagoJpaController pagoController;
    //Variables usadas para desplegar el formulario deslizante
    private Timer timerDeslizamiento;
    private boolean desplegado = false;
    private int anchoObjetivo = 490; // Ancho deseado del formulario
    private int velocidadDeslizamiento = 20; // Aumentado para animación más fluida
    private int anchoActual = 0;
    
}
